DROP TABLE IF EXISTS bloodbank;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS bloodstock;

CREATE TABLE bloodbank (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT UNIQUE NOT NULL
);

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  bloodbank_id INTEGER NOT NULL
);


CREATE TABLE bloodstock (
  id INTEGER PRIMARY KEY,
  blood_type TEXT NOT NULL,
  blood_group TEXT NOT NULL,
  rhesus TEXT NOT NULL,
  created TEXT NOT NULL,
  room INTEGER,
  fridge INTEGER,
  shelf INTEGER,
  bloodbank_id INTEGER NOT NULL
);
